# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 770)
        MainWindow.setStyleSheet("background-color: rgb(74, 74, 74);")
        self.center = QtWidgets.QWidget(MainWindow)
        self.center.setObjectName("center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.center)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_container = QtWidgets.QFrame(self.center)
        self.left_container.setMaximumSize(QtCore.QSize(275, 16777215))
        self.left_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_container.setObjectName("left_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.slide_menu = QtWidgets.QFrame(self.left_container)
        self.slide_menu.setMinimumSize(QtCore.QSize(273, 0))
        self.slide_menu.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.slide_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.slide_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu.setObjectName("slide_menu")
        self.slide_menu.setMaximumWidth(273)
        self.slide_menu.setMinimumWidth(0)
        self.slide_menu.setFixedWidth(0)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.slide_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.slide_menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.foto_perfil = QtWidgets.QFrame(self.frame_2)
        self.foto_perfil.setMinimumSize(QtCore.QSize(120, 120))
        self.foto_perfil.setMaximumSize(QtCore.QSize(120, 120))
        self.foto_perfil.setStyleSheet("background-image: url(:/icons/imagens/foto_perfil.png);\n"
"color: rgb(23, 140, 144);\n"
"border-radius: 60px;\n"
"border: 5px solid rgb(116, 116, 116)")
        self.foto_perfil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foto_perfil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foto_perfil.setObjectName("foto_perfil")
        self.verticalLayout_5.addWidget(self.foto_perfil, 0, QtCore.Qt.AlignHCenter)
        self.lbl_nome_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_nome_2.setStyleSheet("font: 12pt \"Montserrat\";\n"
"color: white;")
        self.lbl_nome_2.setObjectName("lbl_nome_2")
        self.verticalLayout_5.addWidget(self.lbl_nome_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.slide_menu)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_home = QtWidgets.QPushButton(self.frame_4)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_home.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_home.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"color: white;\n"
"font: 11pt \"Century Gothic\";\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/imagens/casa_25x25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(30, 30))
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_11.addWidget(self.btn_home)
        self.btn_add_songs = QtWidgets.QPushButton(self.frame_4)
        self.btn_add_songs.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_add_songs.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_add_songs.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"color: white;\n"
"font: 11pt \"Century Gothic\";\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/imagens/adicionar-botao_br.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_songs.setIcon(icon1)
        self.btn_add_songs.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_songs.setObjectName("btn_add_songs")
        self.verticalLayout_11.addWidget(self.btn_add_songs)
        self.btn_screen_download = QtWidgets.QPushButton(self.frame_4)
        self.btn_screen_download.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_screen_download.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_screen_download.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"color: white;\n"
"font: 11pt \"Century Gothic\";\n"
"text-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"    background-color: rgb(77, 77, 77);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/imagens/download_25x25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_screen_download.setIcon(icon2)
        self.btn_screen_download.setIconSize(QtCore.QSize(30, 30))
        self.btn_screen_download.setObjectName("btn_screen_download")
        self.verticalLayout_11.addWidget(self.btn_screen_download)
        self.verticalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.slide_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.slide_menu)
        self.horizontalLayout.addWidget(self.left_container)
        self.right_conteiner = QtWidgets.QFrame(self.center)
        self.right_conteiner.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_conteiner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_conteiner.setObjectName("right_conteiner")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_conteiner)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top = QtWidgets.QFrame(self.right_conteiner)
        self.top.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.top)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_menu = QtWidgets.QPushButton(self.frame_7)
        self.btn_menu.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_menu.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_menu.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"    background-image: url(:/icons/imagens/menu.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/menu_hover.png);\n"
"}")
        self.btn_menu.setText("")
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_5.addWidget(self.btn_menu)
        self.horizontalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignLeft)
        self.frame_9 = QtWidgets.QFrame(self.top)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.top)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_min = QtWidgets.QPushButton(self.frame_8)
        self.btn_min.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_min.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_min.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/minus.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/minus_hover.png);\n"
"}")
        self.btn_min.setText("")
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_4.addWidget(self.btn_min)
        self.btn_max_min = QtWidgets.QPushButton(self.frame_8)
        self.btn_max_min.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_max_min.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_max_min.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"    background-image: url(:/icons/imagens/max.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/max_hover.png);\n"
"}")
        self.btn_max_min.setText("")
        self.btn_max_min.setObjectName("btn_max_min")
        self.horizontalLayout_4.addWidget(self.btn_max_min)
        self.btn_exit = QtWidgets.QPushButton(self.frame_8)
        self.btn_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_exit.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/x.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/x_hover.png);\n"
"}")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_4.addWidget(self.btn_exit)
        self.horizontalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.top, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.right_conteiner)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setSpacing(11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(256, 256))
        self.frame_6.setMaximumSize(QtCore.QSize(256, 256))
        self.frame_6.setStyleSheet("background-image: url(:/icons/imagens/logo.ico);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7.addWidget(self.frame_6)
        self.label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(212, 212, 213);")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.widget)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_15 = QtWidgets.QFrame(self.page_2)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame_17)
        self.label_2.setStyleSheet("color: white;\n"
"font: 25pt \"Century Gothic\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_10.addWidget(self.frame_17, 0, QtCore.Qt.AlignHCenter)
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.link_youtube = QtWidgets.QLineEdit(self.frame_16)
        self.link_youtube.setMinimumSize(QtCore.QSize(750, 61))
        self.link_youtube.setMaximumSize(QtCore.QSize(779, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.link_youtube.setFont(font)
        self.link_youtube.setStyleSheet("border: 2px solid #00A9E2;\n"
"color: white;")
        self.link_youtube.setInputMask("")
        self.link_youtube.setText("")
        self.link_youtube.setFrame(True)
        self.link_youtube.setCursorPosition(0)
        self.link_youtube.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.link_youtube.setClearButtonEnabled(True)
        self.link_youtube.setObjectName("link_youtube")
        self.horizontalLayout_10.addWidget(self.link_youtube)
        self.btn_download = QtWidgets.QPushButton(self.frame_16)
        self.btn_download.setMinimumSize(QtCore.QSize(91, 61))
        self.btn_download.setMaximumSize(QtCore.QSize(91, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_download.setFont(font)
        self.btn_download.setStyleSheet("QPushButton {\n"
"    border: 0px solid #00A9E2;\n"
"    color: white;\n"
"    background-color: #00A9E2;\n"
"    border-radius: 5px;\n"
"    margin-left: -3px;\n"
"    \n"
"    font: 11pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(0, 183, 244)\n"
"}")
        self.btn_download.setObjectName("btn_download")
        self.horizontalLayout_10.addWidget(self.btn_download)
        self.verticalLayout_10.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_9.setContentsMargins(-1, 16, -1, -1)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_save_in = QtWidgets.QLabel(self.frame_18)
        self.lbl_save_in.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: white;")
        self.lbl_save_in.setObjectName("lbl_save_in")
        self.horizontalLayout_9.addWidget(self.lbl_save_in)
        self.btn_select = QtWidgets.QPushButton(self.frame_18)
        self.btn_select.setMinimumSize(QtCore.QSize(141, 35))
        self.btn_select.setMaximumSize(QtCore.QSize(141, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_select.setFont(font)
        self.btn_select.setStyleSheet("QPushButton {\n"
"    border: 0px solid #00A9E2;\n"
"    color: white;\n"
"    background-color: #00A9E2;\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 11pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(0, 183, 244)\n"
"}")
        self.btn_select.setObjectName("btn_select")
        self.horizontalLayout_9.addWidget(self.btn_select)
        self.verticalLayout_10.addWidget(self.frame_18, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_19 = QtWidgets.QFrame(self.page_3)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.search_music_home = QtWidgets.QLineEdit(self.frame_20)
        self.search_music_home.setMinimumSize(QtCore.QSize(750, 61))
        self.search_music_home.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.search_music_home.setFont(font)
        self.search_music_home.setStyleSheet("border: 2px solid #00A9E2;\n"
"color: white;")
        self.search_music_home.setInputMask("")
        self.search_music_home.setText("")
        self.search_music_home.setFrame(True)
        self.search_music_home.setCursorPosition(0)
        self.search_music_home.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.search_music_home.setClearButtonEnabled(True)
        self.search_music_home.setObjectName("search_music_home")
        self.horizontalLayout_12.addWidget(self.search_music_home)
        self.btn_search_home = QtWidgets.QPushButton(self.frame_20)
        self.btn_search_home.setMinimumSize(QtCore.QSize(91, 61))
        self.btn_search_home.setMaximumSize(QtCore.QSize(91, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search_home.setFont(font)
        self.btn_search_home.setStyleSheet("QPushButton {\n"
"    border: 0px solid #00A9E2;\n"
"    color: white;\n"
"    background-color: #00A9E2;\n"
"    border-radius: 5px;\n"
"    margin-left: -3px;\n"
"    \n"
"    font: 11pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(0, 183, 244)\n"
"}")
        self.btn_search_home.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/imagens/search_hover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search_home.setIcon(icon3)
        self.btn_search_home.setIconSize(QtCore.QSize(60, 60))
        self.btn_search_home.setObjectName("btn_search_home")
        self.horizontalLayout_12.addWidget(self.btn_search_home)
        self.verticalLayout_13.addWidget(self.frame_20)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_19)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableWidget)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.bottom = QtWidgets.QFrame(self.right_conteiner)
        self.bottom.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottom)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.bottom)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.logo_bar = QtWidgets.QFrame(self.frame_10)
        self.logo_bar.setMinimumSize(QtCore.QSize(65, 65))
        self.logo_bar.setMaximumSize(QtCore.QSize(65, 65))
        self.logo_bar.setStyleSheet("background-image: url(:/icons/imagens/Logo 65x65.png);")
        self.logo_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_bar.setObjectName("logo_bar")
        self.horizontalLayout_8.addWidget(self.logo_bar)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_name_Music = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_name_Music.setFont(font)
        self.lbl_name_Music.setStyleSheet("font: 12pt \"Montserrat\";\n"
"color: white;")
        self.lbl_name_Music.setScaledContents(False)
        self.lbl_name_Music.setWordWrap(True)
        self.lbl_name_Music.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_name_Music.setObjectName("lbl_name_Music")
        self.verticalLayout_8.addWidget(self.lbl_name_Music)
        self.lbl_name_Artist = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_name_Artist.setFont(font)
        self.lbl_name_Artist.setStyleSheet("font: 10pt \"Montserrat\";\n"
"color: white;")
        self.lbl_name_Artist.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_name_Artist.setObjectName("lbl_name_Artist")
        self.verticalLayout_8.addWidget(self.lbl_name_Artist)
        self.horizontalLayout_8.addWidget(self.frame_14)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.bottom)
        self.frame_12.setMinimumSize(QtCore.QSize(212, 84))
        self.frame_12.setMaximumSize(QtCore.QSize(212, 84))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_return = QtWidgets.QPushButton(self.frame_12)
        self.btn_return.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_return.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_return.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/anterior.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/anterior_hover.png);\n"
"}")
        self.btn_return.setText("")
        self.btn_return.setObjectName("btn_return")
        self.horizontalLayout_6.addWidget(self.btn_return)
        self.btn_play = QtWidgets.QPushButton(self.frame_12)
        self.btn_play.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_play.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_play.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/toque.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/toque_hover.png);\n"
"}")
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_6.addWidget(self.btn_play)
        self.btn_next = QtWidgets.QPushButton(self.frame_12)
        self.btn_next.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_next.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_next.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/proximo.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/proximo_hover.png);\n"
"}")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_6.addWidget(self.btn_next)
        self.horizontalLayout_3.addWidget(self.frame_12, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_11 = QtWidgets.QFrame(self.bottom)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.frame_11)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/icons/imagens/aleatorio_25x25.png);\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/aleatorio_25x2_br.png);\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.btn_sound = QtWidgets.QPushButton(self.frame_11)
        self.btn_sound.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_sound.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_sound.setStyleSheet("QPushButton {\n"
"border: 0px;\n"
"    background-image: url(:/icons/imagens/volume.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 0px;\n"
"background-image: url(:/icons/imagens/volume_hover.png);\n"
"}")
        self.btn_sound.setText("")
        self.btn_sound.setObjectName("btn_sound")
        self.horizontalLayout_7.addWidget(self.btn_sound)
        self.som_slider = QtWidgets.QSlider(self.frame_11)
        self.som_slider.setMinimumSize(QtCore.QSize(110, 0))
        self.som_slider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color: #00A9E2;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"    border: 0px solid#00A9E2;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: #0092C2;\n"
"    border: 2px solid #0092C2; \n"
"    width: 11px; \n"
"    height: 16px;\n"
"    margin-top: -3px; \n"
"    margin-bottom: -3px;  \n"
"    line-height: 20px; \n"
"    border-radius: 7px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 7px; \n"
"}\n"
"")
        self.som_slider.setOrientation(QtCore.Qt.Horizontal)
        self.som_slider.setObjectName("som_slider")
        self.horizontalLayout_7.addWidget(self.som_slider)
        self.frame_grip = QtWidgets.QFrame(self.frame_11)
        self.frame_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_grip.setStyleSheet("")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_7.addWidget(self.frame_grip, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.bottom)
        self.horizontalLayout.addWidget(self.right_conteiner)
        MainWindow.setCentralWidget(self.center)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ListenNow"))
        self.lbl_nome_2.setText(_translate("MainWindow", "Geovani Debastiani"))
        self.btn_home.setText(_translate("MainWindow", "   Home"))
        self.btn_add_songs.setText(_translate("MainWindow", "   Add Songs"))
        self.btn_screen_download.setText(_translate("MainWindow", "   Download"))
        self.label.setText(_translate("MainWindow", "No Songs Found"))
        self.label_2.setText(_translate("MainWindow", "ListenNow Downloader"))
        self.link_youtube.setPlaceholderText(_translate("MainWindow", " Insert the Youtube link here... "))
        self.btn_download.setText(_translate("MainWindow", "Baixar"))
        self.lbl_save_in.setText(_translate("MainWindow", "Save In:"))
        self.btn_select.setText(_translate("MainWindow", "Select"))
        self.search_music_home.setPlaceholderText(_translate("MainWindow", " Search Music"))
        self.lbl_name_Music.setText(_translate("MainWindow", "Music"))
        self.lbl_name_Artist.setText(_translate("MainWindow", "Artist"))
from View.PY import file_RC


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
