# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 671)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/imagens/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(74, 74, 74);")
        self.center = QtWidgets.QWidget(MainWindow)
        self.center.setObjectName("center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.center)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide_menu = QtWidgets.QFrame(self.center)
        self.slide_menu.setMaximumSize(QtCore.QSize(275, 16777215))
        self.slide_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.slide_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu.setObjectName("slide_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.slide_menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.slide_menu)
        self.frame_3.setMinimumSize(QtCore.QSize(273, 0))
        self.frame_3.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setMinimumSize(QtCore.QSize(120, 120))
        self.label_3.setMaximumSize(QtCore.QSize(120, 120))
        self.label_3.setStyleSheet("background-image: url(:/icons/imagens/foto_perfil.png);\n"
"color:#006F75;\n"
"border-radius: 60px;\n"
"border: 5px solid rgb(170, 170, 170);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_15)
        self.label_4.setStyleSheet("color: gray;\n"
"font: 12pt \"Montserrat\";")
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalLayout_6.addWidget(self.frame_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame_13, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_5.setSizeIncrement(QtCore.QSize(0, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(81, 81, 81);\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_13.addWidget(self.pushButton_5)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_10.setSizeIncrement(QtCore.QSize(0, 41))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left;\n"
"    image-align: left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(81, 81, 81);\n"
"\n"
"}")
        self.pushButton_10.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_13.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_11.setSizeIncrement(QtCore.QSize(0, 41))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(81, 81, 81);\n"
"\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_13.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 41))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(17, 98, 102);\n"
"    color: white;\n"
"    font: 10pt \"Montserrat\";\n"
"    text-align: left\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(81, 81, 81);\n"
"\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_13.addWidget(self.pushButton_12)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.slide_menu)
        self.right_conteiner = QtWidgets.QFrame(self.center)
        self.right_conteiner.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_conteiner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_conteiner.setObjectName("right_conteiner")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_conteiner)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.right_conteiner)
        self.frame_6.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_4.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_4.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/menu.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/menu_hover.png);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignLeft)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setStyleSheet("color: white;\n"
"font: 16pt \"Montserrat\";")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/minus.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/minus_hover.png);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/max.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/max_hover.png);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/x.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/x_hover.png);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.right_conteiner)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.page)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMinimumSize(QtCore.QSize(269, 256))
        self.frame_17.setMaximumSize(QtCore.QSize(269, 256))
        self.frame_17.setStyleSheet("background-image: url(:/icons/imagens/logo.ico);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10.addWidget(self.frame_17)
        self.verticalLayout_9.addWidget(self.frame_16, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.frame_14)
        self.label_2.setStyleSheet("color: gray;\n"
"font: 16pt \"Montserrat\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.verticalLayout_8.addWidget(self.frame_14, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.right_conteiner)
        self.frame_4.setStyleSheet("\n"
"background-color: rgb(63, 63, 63);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_19 = QtWidgets.QFrame(self.frame_10)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMinimumSize(QtCore.QSize(65, 65))
        self.frame_20.setMaximumSize(QtCore.QSize(65, 65))
        self.frame_20.setStyleSheet("background-image: url(:/icons/imagens/Logo 65x65.png);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12.addWidget(self.frame_20)
        self.horizontalLayout_8.addWidget(self.frame_19, 0, QtCore.Qt.AlignLeft)
        self.frame_18 = QtWidgets.QFrame(self.frame_10)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_18)
        self.label_6.setStyleSheet("color: white;\n"
"font: 12pt \"Montserrat\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.frame_18)
        self.label_5.setStyleSheet("color: white;\n"
"font: 10pt \"Montserrat\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.horizontalLayout_8.addWidget(self.frame_18, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setSpacing(19)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    \n"
"    background-image: url(:/icons/imagens/anterior.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/anterior_hover.png);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_9.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_9.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/toque.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/toque_hover.png);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_8.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_8.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/proximo.png);\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/proximo_hover.png);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.horizontalLayout_3.addWidget(self.frame_12, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 30, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_6.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    border: 0px solid;\n"
"    outline: 0;\n"
"    background-image: url(:/icons/imagens/volume.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(:/icons/imagens/volume_hover.png);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.volume_slider = QtWidgets.QSlider(self.frame_11)
        self.volume_slider.setMinimumSize(QtCore.QSize(100, 0))
        self.volume_slider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.volume_slider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color:#00A9E2;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"    border: 0px solid rgb #00A9E2;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: rgb(0, 146, 194);\n"
"    border: 2px solid  rgb(0, 146, 194); \n"
"    width: 11px; \n"
"    height: 16px;\n"
"    margin-top: -3px; \n"
"    margin-bottom: -3px;  \n"
"    line-height: 20px; \n"
"    border-radius: 7px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 7px; \n"
"}\n"
"")
        self.volume_slider.setMaximum(10)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_6.addWidget(self.volume_slider)
        self.horizontalLayout_3.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.right_conteiner)
        MainWindow.setCentralWidget(self.center)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ListenNow"))
        self.label_4.setText(_translate("MainWindow", "Geovani Debastiani"))
        self.pushButton_5.setText(_translate("MainWindow", "     Home"))
        self.pushButton_10.setText(_translate("MainWindow", "     Add Songs"))
        self.pushButton_11.setText(_translate("MainWindow", "     Remove Songs"))
        self.pushButton_12.setText(_translate("MainWindow", "     Download Songs"))
        self.label.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "Nenhuma Música Encontrada"))
        self.label_6.setText(_translate("MainWindow", "Música"))
        self.label_5.setText(_translate("MainWindow", "Artista"))
from View.PY import file_RC
